### ISSUE TITLE
PNPM

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [whosydd/stylelint-config#1]
Could you add pnpm please

**Comment by whosydd** [comment]
https://github.com/whosydd/stylelint-config/releases/tag/1.3.0-pnpm

Try this, hope it works. Just download it and install. If it was terrible, please let me know.

**Comment by jojojojojoj5564656465465** [comment]
yes it's exactly could you upgrade yours

**Comment by whosydd** [comment]
If i add new feat in the future, you will see it. It's not in my plan now. This branch just for you, hope you like it.

**Comment by whosydd** [comment]
> yes it's exactly could you upgrade yours

surprise! you can use it now.
[1.3.0 new!](https://marketplace.visualstudio.com/items?itemName=whosydd.stylelint-config)

btw, maybe you will like this [prettier config](https://marketplace.visualstudio.com/items?itemName=whosydd.prettier-config)

**Comment by jojojojojoj5564656465465** [comment]
I really like it thanks for sharing
